#!/usr/bin/env/python3
# -*- coding: utf-8 -*-
# test.py
from pubmed import OneFilePubmud, Article
root = OneFilePubmud('pubmed1.txt')

print('测试isinstance(root["29389565"], Article)')
print(isinstance(root["29389565"], Article))
print('================================')
print()
print('测试root["29389565"]["时间"]')
print(root["29389565"]["时间"])
print('================================')
print()
print('测试get_value("29389565", "时间")')
print(root.get_value('29389565', '时间'))
print('================================')
print()
print('测试get_value("29389565", ["时间", "作者"])')
print(root.get_value('29389565', ['时间', '作者']))
print('================================')
print()
print('测试yield_all("PMID")')
for title in root.yield_all('PMID'):
    print(title)
print('================================')
print()
print('测试yield_all(["PMID", "时间"])')
for elems in root.yield_all(['PMID', '时间']):
    print(elems)
print('================================')
print()
print("测试get_all('PMID')")
print(root.get_all('PMID'))
print('================================')
print()
print("测试get_all('PMID', '时间')")
print(root.get_all(['PMID', '时间']))
print('================================')
print()
print("测试yield_element('29389565', '时间')")
for time in root.yield_element('29389565', '时间'):
    print(time)
print('================================')
print()
print("测试yield_element(['29389565', '29370131'], '时间')")
for time in root.yield_element(['29389565', '29370131'], '时间'):
    print(time)
print('================================')
print()
print("测试yield_element('29389565', ['PMID', '时间'])")
for time in root.yield_element('29389565', ['PMID', '时间']):
    print(time)
print('================================')
print()
print("测试yield_element(['29389565', '29370131'], ['PMID', '时间'])")
for time in root.yield_element(['29389565', '29370131'], ['PMID', '时间']):
    print(time)
print('================================')
print()
print("测试get_element('29389565', '时间')")
print(root.get_element('29389565', '时间'))
print('================================')
print()
print("测试get_element(['29389565', '29370131'], '时间')")
print(root.get_element(['29389565', '29370131'], '时间'))
print('================================')
print()
print("测试get_element('29389565', ['PMID', '时间'])")
print(root.get_element('29389565', ['PMID', '时间']))
print('================================')
print()
print("测试get_element(['29389565', '29370131'], ['PMID', '时间'])")
print(root.get_element(['29389565', '29370131'], ['PMID', '时间']))
print('================================')
print()
print("测试root2 = root.copy()")
root2 = root.copy()
print("root == root2为", root == root2)
print("root is root2为", root is root2)
print('================================')
print()
words = ['Soy']
words2 = ['Information']
print("测试make_pages()")
root.make_pages(keys=words, values=words2, ignore=True, filter_article=True)

# root.make_pages(keys=words, values=words2, filter_article=True)